site_name: dspy-profiles
repo_url: https://github.com/nielsgl/dspy-profiles
repo_name: nielsgl/dspy-profiles
edit_uri: tree/main/docs

theme:
  name: material
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark vs light mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.code.annotate
    - content.code.select
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

nav:
  - 'Overview': index.md
  - 'User Guide':
    - 'Quickstart': quickstart.md
    - 'Advanced Usage': advanced-usage.md
  - 'Reference':
    - 'CLI Reference': cli-reference.md
    - 'API Reference': api-reference.md
  - 'About':
    - 'Contributing': contributing.md
    - 'Changelog': changelog.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - toc:
      permalink: true
  - mkdocs-typer
  # - mkdocs-click:
  #     module: dspy_profiles.cli
  #     command: app
  #     depth: 2
  #     style: table

plugins:
  - search
  - section-index
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: true
  - mermaid2
