name: Upload Python Package to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing
      contents: write # Required to create a GitHub Release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python and uv
        uses: ./.github/actions/setup

      - name: Build package
        run: uv build --sdist --wheel

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} --generate-notes

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
