name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  setup:
    uses: ./.github/workflows/reusable-setup.yml

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push to gh-pages branch

    steps:
      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
