name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push to gh-pages branch

    steps:
      - name: Setup Python and uv
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Deploy documentation
        run: uv run mkdocs gh-deploy --force
