name: Upload Python Package to PyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Match tags like v0.1.0, v1.2.3 etc.

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Build package
        run: uv build --sdist --wheel

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
