name: Upload Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing

    steps:
      - name: Setup Python and uv
        uses: ./.github/actions/setup

      - name: Build package
        run: uv build --sdist --wheel

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
