name: Upload Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  setup:
    uses: ./.github/workflows/reusable-setup.yml

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing

    steps:
      - name: Build package
        run: uv build --sdist --wheel

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
