name: Upload Python Package to TestPyPI

on:
  release:
    types: [prereleased]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing

    steps:
      - name: Setup Python and uv
        uses: ./.github/actions/setup

      - name: Build package
        run: uv build --sdist --wheel

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
